Repository Kim-s-Crew/SpaghettiCodingClub-FE, pull requests merged in 2024-06, with the labels that each got.

#27 fix : 로그삭제 swal -> 커스텀 모달, toastify 추가
  package.json
  src/app/admin/student/[userId]/page.tsx
  src/app/providers.tsx
  yarn.lock
Labels: 🩹 fix

#28 add : 사용자트랙변경 api 연결
  src/apis/student.ts
  src/app/admin/student/[userId]/page.tsx
  src/components/admin/student/StudentInfo.tsx
  src/types/types.d.ts
Labels: 🎉add, 🩹 fix

#31 add : 일정 생성 api 연결
  src/apis/schedule.ts
  src/app/admin/schedule/planBpage.tsx
  src/components/admin/schedule/ScheduleInput.tsx
  src/types/types.d.ts
Labels: 🎉add

#32 Feat/track week
  src/apis/assesment.ts
  src/apis/auth.ts
  src/apis/schedule.ts
  src/apis/student.ts
  src/apis/track.ts
  src/apis/trackNotice.ts
  src/apis/trackWeek.ts
  src/app/admin/notice/[noticeId]/page.tsx
  src/app/admin/notice/write/page.tsx
  src/app/admin/student/[userId]/page.tsx
  src/app/admin/teambuilding/page.tsx
  src/app/admin/track/page.tsx
  src/app/admin/trackweek/page.tsx
  src/components/admin/TrackSelector.tsx
  src/components/admin/WeekSelector.tsx
  src/components/admin/student/StudentComment.tsx
  src/components/admin/student/StudentInfo.tsx
  src/zustand/store.ts
Labels: 🎉add, 🩹 fix, ✨ update

#33 Feat/track week
  src/apis/team.ts
  src/apis/trackWeek.ts
  src/app/admin/layout.tsx
  src/app/admin/notice/[noticeId]/page.tsx
  src/app/admin/notice/page.tsx
  src/app/admin/student/page.tsx
  src/app/admin/teambuilding/page.tsx
  src/app/admin/trackweek/page.tsx
  src/components/admin/Header.tsx
  src/components/admin/WeekSelector.tsx
  src/types/types.d.ts
  src/zustand/store.ts
Labels: 🎉add, 🩹 fix, ✨ update

#36 update : 팀 조회, 팀생성 api(연결X) (#11)
  src/apis/team.ts
  src/apis/trackWeek.ts
  src/app/admin/teambuilding/page.tsx
  src/app/login/page.tsx
  src/types/types.d.ts
Labels: 🩹 fix, ✨ update

#37 update : 팀 저장 로직 추가 및 404 페이지 작업(#11)
  src/apis/team.ts
  src/app/admin/teambuilding/page.tsx
  src/app/layout.tsx
  src/app/not-found.tsx
  src/types/types.d.ts
Labels: ♻️ refactor, ✨ update

#42 GH actions
  .github/workflows/git-push.yml
Labels: 🤔test

#45 fix : 캘린더 onChange 타입 에러 수정(#12)
  src/app/user/schedule/page.tsx
Labels: 🩹 fix

#46 fix : next 에러 해결
  src/apis/assesment.ts
  src/apis/auth.ts
  src/apis/schedule.ts
  src/apis/student.ts
  src/apis/team.ts
  src/apis/track.ts
  src/apis/trackNotice.ts
  src/apis/trackWeek.ts
  src/app/user/schedule/page.tsx
Labels: 🩹 fix, 🐛 bugfix

#47 fix : next location 오류 해결
  src/app/admin/notice/[noticeId]/page.tsx
  src/app/admin/notice/write/page.tsx
  src/app/login/page.tsx
  src/app/register/page.tsx
  src/components/admin/Header.tsx
  src/components/user/Header.tsx
Labels: 🐛 bugfix

#49 Feat/my page
  src/apis/auth.ts
  src/app/admin/mypage/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/providers.tsx
  src/app/user/askadmin/page.tsx
  src/app/user/layout.tsx
  src/app/user/mypage/page.tsx
  src/app/user/notice/[noticeId]/page.tsx
  src/app/user/notice/page.tsx
  src/app/user/page.tsx
  src/assets/images/warning.webp
  src/components/admin/Header.tsx
  src/components/common/MyPage.tsx
  src/components/ui/Footer.tsx
  src/components/ui/UpdatePassword.tsx
  src/components/user/Header.tsx
  src/hooks/useApiError.ts
  src/hooks/useRole.ts
  src/types/types.d.ts
  src/zustand/store.ts
Labels: 🎉add, 🩹 fix

#51 여러가지 기능 추가 및 코드 수정 + 디자인
  public/favicon.ico
  src/apis/auth.ts
  src/app/admin/page.tsx
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/redirect/page.tsx
  src/app/user/notice/page.tsx
  src/app/user/page.tsx
  src/components/common/MyPage.tsx
  src/components/user/notice/NoticeSection.tsx
  src/hooks/useRole.ts
Labels: 🎉add, 🩹 fix, ✨ update

#52 fix : 수강생 트랙 수정 기능
  src/apis/student.ts
  src/app/admin/notice/page.tsx
  src/app/admin/page.tsx
  src/app/admin/student/[userId]/page.tsx
  src/app/admin/student/page.tsx
  src/app/admin/teambuilding/page.tsx
  src/app/admin/track/page.tsx
  src/app/admin/trackweek/page.tsx
  src/app/redirect/page.tsx
  src/components/admin/Header.tsx
  src/components/admin/student/StudentInfo.tsx
Labels: 🩹 fix

#53 로그인 로직 수정
  src/app/redirect/page.tsx
  src/assets/images/logoutIcon.webp
  src/components/admin/Header.tsx
  src/components/user/Header.tsx
  src/types/types.d.ts
Labels: 🩹 fix, 💄 style

#54 style : 각종 스타일 추가(#13)
  src/app/admin/layout.tsx
  src/app/admin/teambuilding/page.tsx
  src/app/globals.css
  src/app/page.tsx
  src/app/redirect/page.tsx
  src/app/user/layout.tsx
  src/app/user/schedule/page.tsx
  src/assets/images/logoutIcon.svg
  src/assets/images/logoutIcon.webp
  src/components/admin/Header.tsx
  src/components/ui/Footer.tsx
  src/components/user/Header.tsx
  tailwind.config.ts
Labels: 💄 style

#55 update : 메인 페이지 로직 추가
  src/app/page.tsx
  src/app/redirect/page.tsx
Labels: 🩹 fix, ✨ update

#58 add : 이름 변경 기능 추가, WIP toast 추가(#19)
  src/apis/student.ts
  src/app/admin/student/[userId]/page.tsx
  src/components/admin/student/StudentTrackInfo.tsx
  src/components/user/Header.tsx
  src/components/user/team/TeamSection.tsx
  src/hooks/useToast.ts
Labels: 🩹 fix, ✨ update
