Repository Kim-s-Crew/SpaghettiCodingClub-FE, pull requests merged in 2024-05, with the labels that each got.

#8 add: 공지사항 글쓰기 & 전역 상태관리 추가(trackSelector) (#7)
  package.json
  src/app/admin/notice/page.tsx
  src/app/admin/notice/write/page.tsx
  src/components/admin/TrackSelector.tsx
  src/zustand/store.ts
  yarn.lock
Labels: 🎉add, 🔨 script, ✨ update

#14 react-hook-form 도입 / 커스텀모달 적용
  package.json
  src/app/admin/schedule/page.tsx
  src/app/login/page.tsx
  src/app/register/page.tsx
  src/components/admin/schedule/ScheduleInput.tsx
  yarn.lock
Labels: 🎉add, 🔨 script, ✨ update

#15 fix : 시간 시각화 코드 수정
  src/app/admin/schedule/page.tsx
  src/assets/images/123.png
  src/components/admin/schedule/ScheduleBar.tsx
  src/components/admin/schedule/ScheduleInput.tsx
  src/components/admin/schedule/ScheduleVisualizer.tsx
Labels: 🎉add, 🩹 fix

#16 script : axios, react-query 설치
  package.json
  src/app/admin/schedule/page.tsx
  yarn.lock
Labels: 🔨 script

#17 add : 회원가입 / 로그인 api 연결(#10)
  .gitignore
  .prettierrc
  src/app/apis/auth.ts
  src/app/login/page.tsx
  src/app/register/page.tsx
  src/types/types.d.ts
Labels: 🎉add

#18 debug : draggable handle err 문제 해결
  src/app/admin/teambuilding/page.tsx
  src/app/page.tsx
  src/components/admin/teambuilding/Member.tsx
  src/components/admin/teambuilding/Team.tsx
Labels: 🎉add, 🩹 fix, 🐛 bugfix

#23 add : 트랙 공지 api 연결 (#22)
  src/apis/assesment.ts
  src/apis/auth.ts
  src/apis/student.ts
  src/apis/track.ts
  src/apis/trackNotice.ts
  src/app/admin/notice/[noticeId]/page.tsx
  src/app/admin/notice/page.tsx
  src/app/admin/notice/write/page.tsx
  src/app/admin/schedule/page.tsx
  src/app/admin/student/[userId]/page.tsx
  src/app/admin/student/page.tsx
  src/app/admin/teambuilding/page.tsx
  src/app/admin/track/page.tsx
  src/components/admin/Header.tsx
  src/components/ui/Modal.tsx
  src/components/ui/PlusButton.tsx
  src/types/types.d.ts
Labels: 🎉add, ✨ update, 🐛 bugfix
